project_id = "upvjkrbxhwrhbfcetaev"

[functions.sync-hospitals]
verify_jwt = false

[functions.sync-hospitals-nationwide]
verify_jwt = false

[functions.fetch-er-data]
verify_jwt = false

[functions.parse-patient-info]
verify_jwt = false

[functions.fetch-nursing-hospitals]
verify_jwt = false

[functions.fetch-holiday-pharmacies]
verify_jwt = false

[functions.fetch-nearby-pharmacies]
verify_jwt = false

[functions.calculate-acceptance-rate]
verify_jwt = false

[functions.fetch-hospital-details]
verify_jwt = false

[functions.fetch-fire119-stats]
verify_jwt = false

[functions.fetch-moonlight-hospitals]
verify_jwt = false

[functions.sync-pharmacies]
verify_jwt = false

[functions.request-ambulance]
verify_jwt = false
